heat_template_version: 2013-05-23

description: A template to create Cheft server with a Workstation and 2 nodes

parameters:
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach instance to.
    default: public
  instance_num:
    type: number
    label: Instance number
    description: Number of instances.
    default: 3

resources:
  network:
    type: Lib::MSG::PrivateNetwork
    properties:
      public_network: { get_param: public_network }

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: network }

  web_instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_num }
      resource_def:
        type: Lib::MSG::Instance
        properties:
          instance_name: instance_%index%
          port: { get_param: port }

outputs:
  ip:
    description: The public IP address to access the server.
    value: { get_attr: [web_instances, ip] }
        
