heat_template_version: 2013-05-23

description: A template to create Cheft server with a Workstation and 2 nodes

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: ubuntu_cloud14
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: UPI
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: my_net1
  instance_num:
    type: number
    label: Instance number
    description: Number of instances.
    default: 3

resources:
  web_instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_num }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: instance_%index% 
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: key }
          networks:
            - network: { get_param: private_network }
          user_data:
            str_replace:
              template: |
                #!/bin/bash
                sudo apt-get update
                sudo apt-get install git python

                git clone https://github.com/elicul/OpenStack.git

                python OpenStack/chef_install.py $instance_name
              params:
                $instance_name: { get_attr: [web_instances, name] }
                $server_ip: {}
                $worksation_ip: {}
